name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print event name
      run: echo "Event name: ${{ github.event_name }}"

    - name: Print branch name
      run: echo "Branch name: ${{ github.ref }}"

    - name: List files
      run: |
        ls -R

    - name: Use secret
      run: echo "Secret value: ${{ secrets.MY_SUPER_SECRET_KEY }}"
      env:
        MY_SECRET: ${{ secrets.MY_SUPER_SECRET_KEY }}

    - name: Deploy
      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && env.MY_SECRET != ''
      run: echo "Deploying to production"
